lastChangelogVersion: 15.5.8
modelRoles: 
  default: openai-codex/gpt-5.5:xhigh
  slow: openai-codex/gpt-5.5:xhigh
  smol: deepseek/deepseek-v4-pro
  plan: openai-codex/gpt-5.5:xhigh
  designer: openai-codex/gpt-5.5:high
  task: deepseek/deepseek-v4-pro:xhigh
  vision: openai-codex/gpt-5.5:xhigh
  commit: deepseek/deepseek-v4-pro:high
defaultThinkingLevel: high
compaction: 
  enabled: true
  strategy: context-full
task: 
  eager: false
  maxConcurrency: 32
  maxRecursionDepth: 2
web_search: 
  enabled: true
lsp: 
  enabled: true
  diagnosticsOnWrite: true
astGrep: 
  enabled: true
astEdit: 
  enabled: true
todo: 
  enabled: true
  reminders: true
modelProviderOrder: 
  - ltcraft-aws-anthropic
  - ltcraft-kiro-anthropic
  - deepseek
  - hajimi
theme: 
  dark: dark-one
  light: light-one
symbolPreset: unicode
statusLine: 
  preset: nerd
  separator: powerline-thin
display: 
  shimmer: classic
  showTokenUsage: true
autoResume: false
startup: 
  checkUpdate: false